### ISSUE TITLE
"no cli" causes post_gen_project  to fail

### ISSUE THREAD

**Issue by timhughes** [timhughes/cookiecutter-poetry#5]
```Select command_line_interface:
1 - click
2 - no cli
Choose from 1, 2 [1]: 2
use_jupyterlab [y]: y
add_badges [y]: 
Traceback (most recent call last):
  File "/tmp/tmpzyd8_sfl.py", line 24, in <module>
    remove_file(cli_file)
  File "/tmp/tmpzyd8_sfl.py", line 11, in remove_file
    os.remove(os.path.join(PROJECT_DIRECTORY, filepath))
FileNotFoundError: [Errno 2] No such file or directory: '/home/thughes/git/jupyter-pyspark-kubernetes/src/jupyter-pyspark-kubernetes/cli.py'
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

**Comment by timhughes** [comment]
Fixed an test added
